import Link from 'next/link';
import { ArrowLeft, FileClock, FileSpreadsheet, ShieldCheck } from 'lucide-react';
import CostModuleFrame from '@/app/components/CostModuleFrame';

const columns = [
  'Periode',
  'Source File / Version',
  'Uploader',
  'Perubahan CC',
  'Fixed Rows',
  'Variable Rows',
  'Generated By / At',
  'Status',
];

export default function CycleHistoryPage() {
  return (
    <CostModuleFrame
      title="Riwayat Cycle SAP"
      subtitle="Cost Structure & Fluktuasi Biaya · Audit & Generation History"
      contentClassName="p-4 sm:p-6 lg:p-8"
    >
      <div className="mx-auto max-w-7xl space-y-6">
        <section data-cost-motion className="rounded-2xl border border-border bg-card p-6 shadow-sm">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <div className="mb-3 flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary">
                <FileClock size={20} />
              </div>
              <h1 className="text-xl font-bold text-foreground">Riwayat upload dan generation</h1>
              <p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">
                Halaman ini akan menampilkan versi source cycle, Receiver CC yang berubah, reference yang digunakan, validation issue, dan identitas file Fixed/Variable yang dihasilkan. Histori bersifat audit evidence dan tidak menjadi sumber otomatis portion saat CC diaktifkan kembali.
              </p>
            </div>
            <Link
              href="/cost-structure/cycle"
              className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent"
            >
              <ArrowLeft size={16} /> Kembali ke Proses Cycle
            </Link>
          </div>
        </section>

        <section data-cost-motion className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
          <div className="flex items-center justify-between border-b border-border px-5 py-4">
            <div>
              <h2 className="font-semibold text-foreground">Struktur riwayat</h2>
              <p className="mt-1 text-xs text-muted-foreground">Data akan diisi oleh API history setelah persistence lane terintegrasi.</p>
            </div>
            <ShieldCheck className="text-primary" size={20} />
          </div>
          <div className="overflow-x-auto">
            <table className="min-w-full text-left text-sm">
              <thead className="bg-muted/50 text-xs uppercase tracking-wide text-muted-foreground">
                <tr>
                  {columns.map((column) => (
                    <th key={column} className="whitespace-nowrap px-4 py-3 font-semibold">{column}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td colSpan={columns.length} className="px-6 py-14 text-center">
                    <FileSpreadsheet className="mx-auto mb-3 text-muted-foreground/50" size={34} />
                    <p className="font-medium text-foreground">Belum ada data Cycle pada foundation branch</p>
                    <p className="mt-1 text-sm text-muted-foreground">Riwayat akan terbentuk setelah workflow upload dan generation aktif.</p>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>
      </div>
    </CostModuleFrame>
  );
}
