import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { completeRawV2Upload,RawV2DuplicateUploadError } from './completion-service';

const parsed={sources:[],rows:[],issues:[]};
test('Raw V2 completion hashes bytes and delegates period-scoped duplicate lookup',async()=>{let received='';await assert.rejects(()=>completeRawV2Upload({objectKey:'new',expectedSize:3,context:{companyCode:'2000',fiscalYear:2026,fiscalPeriod:8}},{download:async()=>new Uint8Array([1,2,3]),remove:async()=>undefined,findDuplicate:async hash=>{received=hash;return {id:1};},parse:async()=>parsed,persist:async()=>({})}),RawV2DuplicateUploadError);assert.equal(received.length,64);});
test('replayed completion never deletes the already persisted active object',async()=>{let removed=false;await assert.rejects(()=>completeRawV2Upload({objectKey:'same',expectedSize:1,context:{companyCode:'2000',fiscalYear:2026,fiscalPeriod:8}},{download:async()=>new Uint8Array([1]),remove:async()=>{removed=true;},findDuplicate:async()=>({storageKey:'same'}),parse:async()=>parsed,persist:async()=>({})}),RawV2DuplicateUploadError);assert.equal(removed,false);});
test('Raw V2 routes enforce auth and activation only for error-free parsing',()=>{const root=path.resolve('app/api/cost-structure/raw-v2/uploads');const init=readFileSync(path.join(root,'init/route.ts'),'utf8'),complete=readFileSync(path.join(root,'complete/route.ts'),'utf8'),list=readFileSync(path.join(root,'route.ts'),'utf8');assert.match(init,/requireCostStructurePrepare/);assert.match(complete,/requireCostStructurePrepare/);assert.match(list,/requireCostStructureRead/);assert.match(complete,/if \(!hasErrors\)/);assert.match(complete,/status: hasErrors \? "INVALID" : "VALIDATED"/);assert.match(complete,/isActiveVersion: false/);for(const source of [init,complete,list]){assert.doesNotMatch(source,/\.costUpload\b|\.costPeriod\b|activeCalculationRunId|CostCalculationRun/);}});
test('Stage C source migration is additive, numeric, unique, and isolated',()=>{const migration=readFileSync(path.resolve('prisma/migrations/20260904150000_add_cost_raw_v2_sources/migration.sql'),'utf8');assert.doesNotMatch(migration,/^\s*(DROP|DELETE|TRUNCATE|UPDATE|RENAME)\b/im);assert.match(migration,/DECIMAL\(20,2\)/);assert.match(migration,/uploadId_logicalSourceCode_key/);assert.doesNotMatch(migration,/"cost_(periods|uploads|source_rows|validation_issues|calculation_runs)"/);});
