import assert from 'node:assert/strict';
import test from 'node:test';
import * as XLSX from 'xlsx';
import { parseRawAmount,parseRawV2Workbook } from '.';

function tb(options:{period?:number;duplicate?:boolean;mismatch?:boolean;invalid?:boolean;january?:boolean}={}){const period=options.january?1:options.period??8;const headers=['FS Item/Account',` FY   2026  1 - ${period} `,...(period===1?[]:[`FY 2026 1-${period-1}`]),'Variance'];const row=(label:string,current:unknown,prior:unknown,variance:unknown)=>period===1?[label,current,variance]:[label,current,prior,variance];const rows=[['report'],headers,['Calculated profit /*ERGEBNIS*',100,90,10],row('Account /11111111',options.invalid?'bad':100,90,options.mismatch?9:10)];if(options.duplicate)rows.push(row('Duplicate /11111111',100,90,10));return XLSX.utils.aoa_to_sheet(rows);}
function tbTwoRowSap(){return XLSX.utils.aoa_to_sheet([[null,null,null,' FY   2026  1 - 8 ','FY 2026 1 - 7','Variance'],['Currency','Currency Type','FS Item/Account','1 IDR','1 IDR','1 IDR'],['IDR','Company currency','Calculated profit /*ERGEBNIS*',100,90,10],['IDR','Company currency','Account /11111111',100,90,10]]);}
function cc(group:string,options:{debit?:unknown;omitDebit?:boolean;period?:number;from?:number;helper?:boolean;repeat?:boolean;metadataOffset?:number}={}){const rows:unknown[][]=Array.from({length:options.metadataOffset??1},()=>[]);rows.push([null,'Controlling Area','SG01'],[null,'Fiscal Year',2026],[null,'From Period',options.from??options.period??8],[null,'To Period',options.period??8],[null,'Cost Center Group',group],[null,'Cost Elements','Act. Costs',null,null,null,null,null,null,null,null,'Cost Elements','Act Amt','Group CE'],[null,'11111111 Rent',100,null,null,null,null,null,null,null,null,'99999999',999999,'SI2000_PSR']);if(options.repeat)rows.push([null,'Cost Elements','Act. Costs']);rows.push([null,'22222222 Zero',0]);if(!options.omitDebit)rows.push([null,'* Debit',options.debit===undefined?100:options.debit]);rows.push([null,'* Over/Underabsorption',100],[null,'33333333 After debit',500]);return XLSX.utils.aoa_to_sheet(rows);}
function ccInlineSap(group:string){const rows:unknown[][]=[[null,'Cost Centers: Actual/Plan/Variance'],[null,'Date: 04.09.2026'],[null,'Requested by: TEST'],[null,'Controlling Area SGG Controlling Area SGG'],[null,'Fiscal Year 2026'],[null,'From Period 8'],[null,'To Period 8'],[null,'Plan Version 0'],[null,`Cost Center Group ${group} Cost Center synthetic`],[null,'Cost Element Group *'],[],[],[null,'Cost Elements','Act. Costs','Plan Costs','Var.(Abs.)','Var.(%)','Cost Elements','Actual Qty','Plan Qty','Var.(Abs.)','Var.(%)'],[null,'   11111111  Rent',100,0,100,0,'   11111111  Rent',0,0,0,0],[null,'   22222222  Zero',0,0,0,0,'   22222222  Zero',0,0,0,0],[null,'*  Debit',100,0],[null,'** Over/Underabsorption',100,0]];return XLSX.utils.aoa_to_sheet(rows);}
function bytes(sheets:Record<string,XLSX.WorkSheet>){const book=XLSX.utils.book_new();for(const [name,sheet] of Object.entries(sheets))XLSX.utils.book_append_sheet(book,sheet,name);return XLSX.write(book,{type:'buffer',bookType:'xlsx'}) as Uint8Array;}

test('numeric parser accepts explicit negative formats and rejects malformed values',()=>{assert.equal(parseRawAmount('(1,000)')?.toString(),'-1000');assert.equal(parseRawAmount('1,000-')?.toString(),'-1000');assert.equal(parseRawAmount('-1,000')?.toString(),'-1000');assert.equal(parseRawAmount('not money'),null);assert.equal(parseRawAmount('') ,null);});
test('semantic TB parser preserves summary lineage and validates exact variance',async()=>{const parsed=await parseRawV2Workbook(bytes({TB:tb(),ADUM:cc('SI2000_ADM',{repeat:true,metadataOffset:4}),PASAR:cc('SI2000_PSR')}),{companyCode:'2000',fiscalYear:2026,fiscalPeriod:8});const source=parsed.sources.find(s=>s.logicalSourceCode==='TB');assert.equal(source?.fiscalPeriod,8);assert.equal(source?.detailRowCount,1);assert.equal(parsed.rows.find(r=>r.descriptionRaw?.includes('Calculated profit'))?.normalizationStatus,'NON_FINANCIAL_LINEAGE');assert.equal(parsed.rows.find(r=>r.coaCodeRaw==='11111111'&&r.logicalSourceCode==='TB')?.amount,'10.00');assert.equal(parsed.issues.filter(i=>i.severity==='ERROR').length,0);});
test('real SAP-shaped two-row TB header and inline CC metadata parse by content',async()=>{const parsed=await parseRawV2Workbook(bytes({TB:tbTwoRowSap(),'Administrative raw':ccInlineSap('SI2000_ADM'),'Marketing raw':ccInlineSap('SI2000_PSR'),'Derivative raw':ccInlineSap('SI2000_DRV')}),{companyCode:'2000',fiscalYear:2026,fiscalPeriod:8});assert.deepEqual(parsed.detectedPeriod,{fiscalYear:2026,fiscalPeriod:8});assert.equal(parsed.sources.find(s=>s.logicalSourceCode==='TB')?.detailRowCount,1);for(const [code,group] of [['CC_ADUM','SI2000_ADM'],['CC_PASAR','SI2000_PSR'],['CC_DERIV','SI2000_DRV']] as const){const source=parsed.sources.find(s=>s.logicalSourceCode===code);assert.equal(source?.costCenterGroup,group);assert.equal(source?.fiscalYear,2026);assert.equal(source?.fiscalPeriod,8);assert.equal(source?.detailRowCount,2);assert.equal(source?.debitControl,'100.00');assert.equal(source?.reconciliationDifference,'0.00');}assert.equal(parsed.sources.find(s=>s.logicalSourceCode==='CC_PROD')?.presenceStatus,'ABSENT_TREATED_AS_ZERO');assert.equal(parsed.issues.filter(i=>i.severity==='ERROR').length,0);});
test('TB duplicate, mismatch, invalid amount, missing header, and selected-period errors fail closed',async()=>{for(const [sheet,code] of [[tb({duplicate:true}),'RAW_TB_DUPLICATE_COA'],[tb({mismatch:true}),'RAW_TB_VARIANCE_MISMATCH'],[tb({invalid:true}),'RAW_TB_INVALID_AMOUNT'],[XLSX.utils.aoa_to_sheet([['nothing']]),'RAW_TB_HEADER_NOT_FOUND']] as const){const parsed=await parseRawV2Workbook(bytes({TB:sheet,ADUM:cc('SI2000_ADM'),PASAR:cc('SI2000_PSR')}),{companyCode:'2000',fiscalYear:2026,fiscalPeriod:8});assert.ok(parsed.issues.some(i=>i.issueCode===code),code);}const wrong=await parseRawV2Workbook(bytes({TB:tb(),ADUM:cc('SI2000_ADM'),PASAR:cc('SI2000_PSR')}),{companyCode:'2000',fiscalYear:2026,fiscalPeriod:9});assert.ok(wrong.issues.some(i=>i.issueCode==='RAW_CROSS_SOURCE_PERIOD_MISMATCH'));});
test('January uses logical zero previous YTD without requiring 1-0',async()=>{const parsed=await parseRawV2Workbook(bytes({TB:tb({january:true}),ADUM:cc('SI2000_ADM',{period:1}),PASAR:cc('SI2000_PSR',{period:1})}),{companyCode:'2000',fiscalYear:2026,fiscalPeriod:1});assert.ok(!parsed.issues.some(i=>i.issueCode==='RAW_TB_PERIOD_COLUMNS_INVALID'));});
test('CC parser classifies content, keeps zero rows, stops at Debit, and ignores columns L+',async()=>{const parsed=await parseRawV2Workbook(bytes({TB:tb(),ADUM:cc('SI2000_ADM',{helper:true}),PASAR:cc('SI2000_PSR'),Derivatif:cc('SI2000_DRV')}),{companyCode:'2000',fiscalYear:2026,fiscalPeriod:8});for(const code of ['CC_ADUM','CC_PASAR','CC_DERIV'])assert.ok(parsed.sources.some(s=>s.logicalSourceCode===code));const adum=parsed.sources.find(s=>s.logicalSourceCode==='CC_ADUM');assert.equal(adum?.detailRowCount,2);assert.equal(adum?.nonZeroDetailRowCount,1);assert.equal(adum?.detailTotal,'100.00');assert.equal(adum?.debitControl,'100.00');assert.equal(adum?.reconciliationDifference,'0.00');assert.ok(!parsed.rows.some(r=>r.coaCodeRaw==='99999999'||r.coaCodeRaw==='33333333'));});
test('CC malformed controls, period range, unknown group, and name conflict are errors',async()=>{const cases:[XLSX.WorkSheet,string,string][]=[[cc('SI2000_ADM',{omitDebit:true}),'ADUM','RAW_CC_DEBIT_NOT_FOUND'],[cc('SI2000_ADM',{debit:null}),'ADUM','RAW_CC_INVALID_AMOUNT'],[cc('SI2000_ADM',{debit:99}),'ADUM','RAW_CC_DETAIL_DEBIT_MISMATCH'],[cc('SI2000_ADM',{from:7}),'ADUM','RAW_CC_PERIOD_RANGE_INVALID'],[cc('UNKNOWN'),'Mystery','RAW_CC_GROUP_UNKNOWN'],[cc('SI2000_ADM'),'PASAR','RAW_SOURCE_CLASSIFICATION_CONFLICT']];for(const [candidate,name,code] of cases){const parsed=await parseRawV2Workbook(bytes({TB:tb(),[name]:candidate,PASAR2:cc('SI2000_PSR')}),{companyCode:'2000',fiscalYear:2026,fiscalPeriod:8});assert.ok(parsed.issues.some(i=>i.issueCode===code),code);}});
test('batch reports required, ambiguous, and explicit optional-zero sources',async()=>{const missing=await parseRawV2Workbook(bytes({TB:tb()}),{companyCode:'2000',fiscalYear:2026,fiscalPeriod:8});assert.equal(missing.issues.filter(i=>i.issueCode==='RAW_SOURCE_REQUIRED_MISSING').length,2);assert.equal(missing.sources.find(s=>s.logicalSourceCode==='CC_PROD')?.presenceStatus,'ABSENT_TREATED_AS_ZERO');assert.equal(missing.sources.find(s=>s.logicalSourceCode==='CC_DERIV')?.presenceStatus,'ABSENT_TREATED_AS_ZERO');assert.equal(missing.issues.filter(i=>i.issueCode==='RAW_OPTIONAL_SOURCE_ABSENT_ZERO').length,2);const duplicate=await parseRawV2Workbook(bytes({TB:tb(),ADUM1:cc('SI2000_ADM'),ADUM2:cc('SI2000_ADM'),PASAR:cc('SI2000_PSR')}),{companyCode:'2000',fiscalYear:2026,fiscalPeriod:8});assert.ok(duplicate.issues.some(i=>i.issueCode==='RAW_SOURCE_AMBIGUOUS'));});
test('a present malformed optional DERIV remains present and blocking',async()=>{const malformed=cc('SI2000_DRV',{omitDebit:true});const parsed=await parseRawV2Workbook(bytes({TB:tb(),ADUM:cc('SI2000_ADM'),PASAR:cc('SI2000_PSR'),DERIV:malformed}),{companyCode:'2000',fiscalYear:2026,fiscalPeriod:8});assert.equal(parsed.sources.find(s=>s.logicalSourceCode==='CC_DERIV')?.presenceStatus,'PRESENT');assert.ok(parsed.issues.some(i=>i.issueCode==='RAW_CC_DEBIT_NOT_FOUND'&&i.severity==='ERROR'));assert.ok(!parsed.issues.some(i=>i.issueCode==='RAW_OPTIONAL_SOURCE_ABSENT_ZERO'&&i.logicalSourceCode==='CC_DERIV'));});
test('a structurally malformed optional DERIV worksheet is blocking and never treated as absent-zero',async()=>{const malformed=XLSX.utils.aoa_to_sheet([[null,'unexpected layout'],[null,'still present but unreadable']]);const parsed=await parseRawV2Workbook(bytes({TB:tb(),ADUM:cc('SI2000_ADM'),PASAR:cc('SI2000_PSR'),DERIV:malformed}),{companyCode:'2000',fiscalYear:2026,fiscalPeriod:8});assert.ok(parsed.sources.some(s=>s.originalSheetName==='DERIV'&&s.presenceStatus==='PRESENT'));assert.ok(parsed.issues.some(i=>i.severity==='ERROR'&&i.originalSheetName==='DERIV'));assert.ok(!parsed.issues.some(i=>i.issueCode==='RAW_OPTIONAL_SOURCE_ABSENT_ZERO'&&i.logicalSourceCode==='CC_DERIV'));});
