'use client';
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useMemo, useState } from 'react';

type AnyRow = Record<string, any>;
function rupiah(value: unknown) { if(value==null)return '—'; const text=String(value), negative=text.startsWith('-'), [whole,fraction]=text.replace('-','').split('.'); return `${negative?'-':''}Rp${whole.replace(/\B(?=(\d{3})+(?!\d))/g,'.')}${fraction&&fraction!=='00'?`,${fraction}`:''}`; }
function Badge({status}:{status:string}) { const pass=['PASS','SUCCESS','READY'].includes(status); const neutral=['NOT RUN','BLOCKED'].includes(status); return <span className={`rounded-full px-3 py-1 text-xs font-bold ${pass?'bg-emerald-100 text-emerald-800':neutral?'bg-slate-100 text-slate-700':'bg-red-100 text-red-800'}`}>{status}</span>; }

export default function ReconciliationDashboard(){
 const [year,setYear]=useState(2026),[period,setPeriod]=useState(8),[data,setData]=useState<AnyRow|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [query,setQuery]=useState(''),[sourceFilter,setSourceFilter]=useState(''),[groupFilter,setGroupFilter]=useState(''),[natureFilter,setNatureFilter]=useState(''),[statusFilter,setStatusFilter]=useState(''),[classFilter,setClassFilter]=useState('');
 async function load(){setBusy(true);setError('');try{const response=await fetch(`/api/cost-structure/raw-v2/report?fiscalYear=${year}&fiscalPeriod=${period}`);const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);}catch(e){setError(e instanceof Error?e.message:'Gagal memuat laporan.');}finally{setBusy(false)}}
 async function calculate(path:string){setBusy(true);setError('');try{const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({companyCode:'2000',fiscalYear:year,fiscalPeriod:period})});const body=await response.json();if(!response.ok)throw new Error(body.error);await load();}catch(e){setError(e instanceof Error?e.message:'Proses gagal.');setBusy(false)}}
 const run=data?.run, rec=data?.stageD?.reconciliation;
 const analytical=useMemo(()=>run?.analyticalRows??[],[run]);
 const filtered=useMemo(()=>analytical.filter((row:AnyRow)=>(!query||`${row.coaCode} ${row.descriptionRaw??''}`.toLowerCase().includes(query.toLowerCase()))&&(!sourceFilter||row.logicalSourceCode===sourceFilter)&&(!groupFilter||row.costGroupCode===groupFilter)&&(!natureFilter||row.natureCode===natureFilter)&&(!statusFilter||row.mappingStatus===statusFilter||row.mappingAction===statusFilter)&&(!classFilter||row.analyticalClass===classFilter)),[analytical,query,sourceFilter,groupFilter,natureFilter,statusFilter,classFilter]);
 const workflows=[['1. Raw upload',data?.upload?.status==='VALIDATED'?'READY':data?.upload?.status??'NOT RUN'],['2. Source validation',data?.upload?.status==='VALIDATED'?'PASS':data?.upload?'FAIL':'NOT RUN'],['3. TB ↔ Base CC reconciliation',rec?.status??'NOT RUN'],['4. Mapping / Rincian / SI',run?.status??(rec?'BLOCKED':'NOT RUN')],['5. Reporting / Export',data?.exportEligibility?.eligible?'READY':'BLOCKED']];
 const cards=[['Final ADUM',data?.executive?.finalAdum],['Final PASAR',data?.executive?.finalPasar],['Final Company SI',data?.executive?.finalCompanySi],['Stage D CC − TB',data?.executive?.stageDDifference],['Rincian ADUM correction',data?.executive?.rincianAdumCorrection],['DERIV raw',data?.executive?.derivRaw],['DERIV contributing',data?.executive?.derivContributing],['DERIV excluded',data?.executive?.derivExcluded],['DERIV SI offset',data?.executive?.derivSiOffset]];
 return <div className="space-y-6">
  <section className="rounded-2xl border border-blue-200 bg-gradient-to-r from-blue-50 to-violet-50 p-6"><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Operational reporting · Company 2000</p><h1 className="mt-2 text-2xl font-bold">Raw SAP Cost Structure & SI</h1><p className="mt-2 text-sm text-slate-600">Active-upload scoped review, persisted results, audit lineage, and controlled export. Ruleset: {run?.ruleSetVersion??'—'}</p></section>
  <section className="flex flex-wrap items-end gap-3 rounded-2xl border bg-white p-5 shadow-sm"><label className="text-sm">Fiscal year<input className="mt-1 block rounded border p-2" type="number" value={year} onChange={e=>setYear(Number(e.target.value))}/></label><label className="text-sm">Period<select className="mt-1 block rounded border p-2" value={period} onChange={e=>setPeriod(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><button onClick={load} disabled={busy} className="rounded bg-slate-700 px-4 py-2 text-white">{busy?'Loading…':'Load period'}</button><button onClick={()=>calculate('/api/cost-structure/raw-v2/reconciliation/calculate')} disabled={busy||data?.upload?.status!=='VALIDATED'} className="rounded bg-blue-600 px-4 py-2 text-white disabled:bg-slate-300">Run reconciliation</button><button onClick={()=>calculate('/api/cost-structure/raw-v2/si/calculate')} disabled={busy||!rec||rec.missingInTbCount>0||rec.derivPasarCoverageMissing>0} className="rounded bg-violet-700 px-4 py-2 text-white disabled:bg-slate-300">Run mapped SI</button>{data?.exportEligibility?.eligible&&<a className="rounded bg-emerald-700 px-4 py-2 font-semibold text-white" href={`/api/cost-structure/raw-v2/report/export?fiscalYear=${year}&fiscalPeriod=${period}`}>Export Excel</a>}{error&&<p className="w-full text-sm font-semibold text-red-700">{error}</p>}</section>
  {data&&<><section className="grid gap-3 md:grid-cols-5">{workflows.map(([label,status])=><div className="rounded-xl border bg-white p-4" key={label}><p className="mb-3 text-xs font-semibold text-slate-600">{label}</p><Badge status={status}/></div>)}</section>
  <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">Period context</h2><p className="text-sm text-slate-600">Company 2000 · {year}/P{String(period).padStart(2,'0')} · period {data.period?.status??'NOT FOUND'} · upload {data.upload?`#${data.upload.id} v${data.upload.version} ${data.upload.status}`:'none'}</p></div>{run&&<Badge status={run.status}/>}</div></section>
  {run&&<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([label,value])=><div key={label} className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-lg font-bold">{rupiah(value)}</p></div>)}</section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Mapping coverage</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th>Population</th><th>Non-zero</th>{['INCLUDE','EXCLUDE','RECLASS','UNMAPPED','AMBIGUOUS','INVALID TARGET'].map(x=><th key={x}>{x}</th>)}<th>Difference</th><th>Status</th></tr></thead><tbody>{run.controls.filter((c:AnyRow)=>c.controlCode.endsWith('_MAPPING_COMPLETENESS')).map((c:AnyRow)=>{const m=c.metricsJson??{};return <tr className="border-t" key={c.id}><td className="py-2 font-bold">{c.sourceLogicalCode}</td><td>{m.nonZeroCount??0}</td>{['include','exclude','reclass','unmapped','ambiguous','invalidTarget'].map(k=><td key={k}>{m[k]?.count??0} · {rupiah(m[k]?.amount)}</td>)}<td>{rupiah(c.difference)}</td><td><Badge status={c.status}/></td></tr>})}</tbody></table></div></section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Nature breakdown (persisted)</h2>{['ADUM','PASAR'].map(group=><div key={group} className="mt-4"><h3 className="font-semibold">{group}</h3><div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{run.results.filter((r:AnyRow)=>r.resultLevel==='NATURE'&&r.costGroupCode===group).map((r:AnyRow)=><tr className="border-t" key={r.id}><td className="py-2 font-mono">{r.natureCode}</td><td>{r.natureName??'—'}</td><td className="text-right font-bold">{rupiah(r.amount)}</td></tr>)}</tbody></table></div></div>)}</section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Analytical lineage</h2><div className="my-3 grid gap-2 md:grid-cols-3 lg:grid-cols-6"><input placeholder="COA / description" className="rounded border p-2 text-sm" value={query} onChange={e=>setQuery(e.target.value)}/>{[['Source',sourceFilter,setSourceFilter,'logicalSourceCode'],['Cost Group',groupFilter,setGroupFilter,'costGroupCode'],['Nature',natureFilter,setNatureFilter,'natureCode'],['Status / action',statusFilter,setStatusFilter,'mappingStatus'],['Class',classFilter,setClassFilter,'analyticalClass']].map(([label,value,setter,key]:any)=><select aria-label={label} className="rounded border p-2 text-sm" key={label} value={value} onChange={e=>setter(e.target.value)}><option value="">All {label}</option>{[...new Set(analytical.map((r:AnyRow)=>r[key]).filter(Boolean))].map((x:any)=><option key={x}>{x}</option>)}</select>)}</div><div className="max-h-[34rem] overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th>Source / sheet / row</th><th>COA / description</th><th>Raw</th><th>SI contribution</th><th>Class</th><th>Status/action</th><th>Target</th><th>Rule / mapping</th><th>References</th></tr></thead><tbody>{filtered.map((r:AnyRow)=><tr className="border-t align-top" key={r.id}><td className="py-2">{r.logicalSourceCode}<br/>{r.originalSheetName} · {r.sourceRowNumber}</td><td><b className="font-mono">{r.coaCode}</b><br/>{r.descriptionRaw}</td><td>{rupiah(r.rawAmount)}</td><td className="font-bold">{rupiah(r.mappedAmount)}</td><td>{r.analyticalClass}</td><td>{r.mappingStatus} / {r.mappingAction??'—'}</td><td>{r.costGroupCode??'—'} / {r.natureCode??'—'}</td><td>{r.ruleCode??'—'}<br/>#{r.mappingId??'—'} · {r.mappingEffectiveDate?.slice(0,10)??'—'}</td><td><details><summary>View JSON</summary><pre className="max-w-sm whitespace-pre-wrap">{JSON.stringify(r.referenceJson,null,2)}</pre></details></td></tr>)}</tbody></table></div></section>
  <section className={`rounded-2xl border p-5 ${data.issues.length||run.controls.some((c:AnyRow)=>c.status!=='PASS')?'border-red-200 bg-red-50':'border-emerald-200 bg-emerald-50'}`}><h2 className="font-bold">Blocking & diagnostic issues</h2>{!data.issues.length&&!run.controls.some((c:AnyRow)=>c.status!=='PASS')?<p className="mt-2 text-sm font-semibold text-emerald-800">Zero blocking issues. All persisted Stage E controls PASS.</p>:<ul className="mt-2 list-disc pl-5 text-sm">{data.issues.map((i:AnyRow)=><li key={i.id}>{i.issueCode}: {i.message}</li>)}{run.controls.filter((c:AnyRow)=>c.status!=='PASS').map((c:AnyRow)=><li key={c.id}>{c.controlCode}: {c.status} ({rupiah(c.difference)})</li>)}</ul>}</section></>}
  <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Run history</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th>Run</th><th>Stage</th><th>Upload</th><th>Status</th><th>State</th><th>Ruleset</th><th>Started / completed</th><th>Rows R/C/A</th><th>Error / invalidation</th></tr></thead><tbody>{data.history.map((h:AnyRow)=><tr className={`border-t ${h.isActive&&h.status==='SUCCESS'?'bg-emerald-50':''}`} key={h.id}><td className="py-2">#{h.runNumber} / ID {h.id}</td><td>{h.stage??'—'}</td><td>#{h.uploadId} / v{h.uploadVersion??'—'}</td><td><Badge status={h.status}/></td><td>{h.isActive?'ACTIVE':'INACTIVE'}</td><td>{h.ruleSetVersion}</td><td>{new Date(h.startedAt).toLocaleString()}<br/>{h.completedAt?new Date(h.completedAt).toLocaleString():'—'}</td><td>{h.resultCount}/{h.controlCount}/{h.analyticalRowCount}</td><td>{h.errorMessage??'—'}</td></tr>)}</tbody></table></div>{!data.exportEligibility.eligible&&<p className="mt-3 text-xs text-amber-800">Export blocked: {data.exportEligibility.reasons.join(' ')}</p>}</section></>}
 </div>
}
